---
machine:
  install:
    diskSelector:
      wwid: "REPLACE_WITH_NODE2_SYSTEM_DISK_WWID"
  certSANs:
    - __NODE2_LAN_IP__
    - __NODE2_IP__
  network:
    hostname: node2
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    interfaces:
      - interface: eth0
        addresses:
          - __NODE2_LAN_IP__/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1

---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data
provisioning:
  diskSelector:
    match: "!system_disk"
  minSize: 10GiB
  maxSize: 10TiB
filesystem:
  type: ext4
